site/neptourapp/urls.py
from django.urls import path, include
from .views import *
from . import views

app_name = 'neptourapp'

urlpatterns = [

    path('navbar/', Home.as_view(), name='navbar'),
    path('', HomeView.as_view(), name='home'),
    path('api/', ApiCreateView.as_view(), name='apicreate'),
    path('api/<int:pk>/', APIRetreiveDestroyDelete.as_view(),
         name='apiretrievedestroydelete'),
    path('registerme/', Registration.as_view(), name='registration'),
    path("login/", LoginView.as_view(), name='login'),
<<<<<<< HEAD
=======
    path('add/post/',AddPost.as_view(),name = 'addpost'),
    path('profile/', ProfileView.as_view(),name = 'profile'),
>>>>>>> 661f34e0e120f4f284f1db991f32d5bfe283440a

    path('search/', PlaceRecommendation.search, name='search'),
    path('package/', Package.as_view(), name='package'),
    path('donation/', Donation.as_view(), name='donation'),



    path('recommendation/', RecommendationView.as_view()),
    path('locations/', FetchAllView.as_view()),

    # path('searchview/', SearchView.as_view(), name='searchview'),

<<<<<<< HEAD
    path('add/post/',AddPost.as_view(),name = 'addpost'),
    path('profile/', ProfileView.as_view(),name = 'profile'),
=======
>>>>>>> 661f34e0e120f4f284f1db991f32d5bfe283440a
    # path("login-in/", views.Loginview, name='login'),




]

site/neptourproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('neptourapp.urls')),
    path('api/', include('neptourapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/templates/addpost.html
{% extends 'navbar.html' %}
{% load static %}
<body>
{% block content %}
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{% comment %} {{ form.as_p }}
	<button>register</button>	 {% endcomment %}


</form>
 <div  class="container" >

        <div class="row">
            <div class="col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-header bg-primary" style="color: white">
                        <h4>Add Post</h4>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Submit</button>

                         
                        {% comment %} <div class="form-group needs-validation" novalidate>
                            <input type="text" class="form-control" id="name" placeholder="Post Title" required>
                        </div>
                        <div class="form-group">
                            <label for="email">{{ form.email.label_tag }}</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                                placeholder="Enter email" required>
                            <small id="emailHelp" class="form-text text-muted"></small>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <label for="confirm-pw">Confirm Password</label>
                            <input type="password" class="form-control" id="confirm-pw" placeholder="Password" required>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div> {% endcomment %}
                    </form>
                </div>
            </div>
        </div>


    </div>



{% endblock %}
</body>

site/templates/donation.html
{% extends 'navbar.html' %} {% load static %} {% block content %}
<h2>Donate</h2>
<h4>If you like our service and want to help us you can donate through:</h4>
<p>Esewa: 9862059111</p>
<p>RBB: 15500xxxxxxxx</p>
<br />
{% endblock %}

site/templates/login1.html
{% if error %}
	<li class="text-danger">{{error}}</li>
{% endif %}	
<form method = "POST">
 	{% csrf_token %}
	 <div class="login">
	    <h1>Login</h1>	
	 	{{ form.as_p }}
	 	<button>Login</button>
	 </div>	

 </form>

site/templates/myhome.html
{% extends 'navbar.html' %}
{% load static %}
<body>
{% block content %}

    <!-- SHOW CAROUSEL -->
    
    <div id="carousel-container">
        <ol class="carousel-indicators">
            <li data-target="#showCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#showCarousel" data-slide-to="1"></li>
            <li data-target="#showCarousel" data-slide-to="2"></li>
        </ol>
        <div id="showCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/lake.jpeg' %}" alt="" class="d-block w-100 img-carousel">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Pokhara</h5>
                        <p>Place of Heaven</p>
                    </div>
                </div>
                <div class="carousel-item ">
                    <img src="{% static 'img/village.jpg' %}" alt="" class="d-block w-100 img-carousel">
                </div>
                <div class="carousel-item ">
                    <img src="{% static 'img/elephant.jpeg' %}" alt="" class="d-block w-100 img-carousel">
                </div>
                 {% comment %} <div class="carousel-item ">
                    <img src="{% static 'img/Rt.jpeg' %}" alt="" class="d-block w-100 img-carousel">
                </div> {% endcomment %}

                <!-- <a class="carousel-control-prev" href="#showCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#showCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span> -->
            </div>
        </div>
    </div>


    <div class="wrapper">
        <div class="#">
            <div class="row">
                {% for post in posts %}

                <div class="col-md-4">
                    <div class="card">
                        <img src="{{ post.image.url }}" alt="" class="card-img-top">
                        <div class="card-body">

                            <h5 class="card-title">Title:{{ post.title }}</a></h5>
                            <h5 class="card-title">Place:{{ post.place }}</h5>
                            <h5 class="card-title"><strong><a href= "{% url 'neptourapp:profile' %}">Photographer:{{ post.photographer }}</strong></a></h5>
                            <p class="card-text">{{ post.description}}</p>
                        </div>

                    </div>
                </div>
                {% endfor %}

                {% comment %} <div class="col-md-4">
                    <div class="card">
                        <img src="{% static 'img/village.jpg' %}" alt="" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">Taplejung</h5>
                            <p class="card-text">Place Description Here...</p>
                        </div>
                    </div>
                </div> {% endcomment %}
            </div>
        </div>
        <!-- <button class="btn btn-primary" data-toggle="modal" data-target="#loginModal">Modal</button> -->
        <!-- wrapper ENDS -->
    </div>
     <div class="modal fade" id="addPostModal">
        
    </div>

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title">
                        <button class=" form-select-btn" id="login-form-btn">Login</button>
                        {% comment %} <button class="form-select-btn" id="register-form-btn">Register</button> {% endcomment %}
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% comment %} <div class="modal-body">
                    <div id="register-form" class="registerForm">

                        <form method = "POST" class = "form" action = "{% url 'neptourapp:navbar' %}>
                            <div class="form-group needs-validation" novalidate>
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" placeholder="Enter Name" required>
                            </div>
                            <div class="form-group">
                                <label for="email">Email address</label>
                                <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                                    placeholder="Enter email" required>
                                <small id="emailHelp" class="form-text text-muted"></small>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" placeholder="Password" required>
                            </div>
                            <div class="form-group">
                                <label for="confirm-pw">Confirm Password</label>
                                <input type="password" class="form-control" id="confirm-pw" placeholder="Password" required>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn submit-btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div> {% endcomment %}

                    <!-- Login Form -->
                    <div id="login-form" class="loginForm">
                        <form method = "GET" class = "form" action = "{% url 'neptourapp:navbar' %}">
                            {% csrf_token %}
                            <div class="form-group needs-validation" novalidate>
                                <label for="email">Email address</label>
                                <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                                    placeholder="Enter email" required>
                                <small id="emailHelp" class="form-text text-muted"></small>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" placeholder="Password" required>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn-close btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn submit-btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

<script>



    // FOR FORM VALIDATION
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            //validate all forms
            // var forms = document.getElementsByTagName('form');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
    // for Showing Login form and Register Form
    
    $('.registerForm').hide()

    $('#login-form-btn').click(function () {
        $('.registerForm').hide()
        $('.loginForm').show()
        $(".submit-btn").modalForm({formURL: "{% url 'neptourapp:login' %}"});


    })

    $('#register-form-btn').click(function () {
        $('.loginForm').hide()

        $('.registerForm').show()
        $(".submit-btn").modalForm({formURL: "{% url 'neptourapp:registration' %}"});



    })


    $('.carousel').carousel({
        interval: 6000
    });

</script>


{% endblock %}
</body>

site/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'>
    {% comment %} <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     {% endcomment %}
    <link rel='stylesheet' href="path/to/font-awesome/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     
      <!-- <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/bootstrap.min.css' %}"
    />  -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css'>

    <title>Nep Tour: Explore Beyond Himalayas</title>
</head>
<body>
   <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'neptourapp:home' %}" class="navbar-brand">Nep Tour</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'neptourapp:addpost' %}" class="nav-link ">Add Post</a>
                    </li>
                    <li class="nav-item" id="categoryItems">
                        <div class="dropdown">
                            {% comment %} <div class='#'><a href="{% url 'neptourapp:registration' %}">Register</a></div> {% endcomment %}

                            <div class="dropdown-menu category-item" aria-labelledby="category">
                                <a class="dropdown-item" href="#">Register</a>
                                <a class="dropdown-item" href="#">Nature</a>
                                <a class="dropdown-item" href="#">Adventure</a>
                                <a class="dropdown-item" href="#">Religious</a>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item"><a href="{% url 'neptourapp:registration' %}" class="nav-link">Register</a></li>
                    <li class="nav-item">
                        <a href="{% url 'neptourapp:search' %}" class="nav-link">Search</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'neptourapp:donation' %}" class="nav-link">Donation</a>
                    </li>
                     <li class="nav-item">
                        <a href="{% url 'neptourapp:package' %}" class="nav-link">Package</a>
                    </li>
                    <li class="nav-item">
                        <div style = 'cursor:pointer' class="nav-link" data-toggle="modal" data-target="#loginModal"><a>Login<a></div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


{% block content %}
{% endblock %}
</body>

</html>

site/templates/package.html
{% extends 'navbar.html' %} {% load static %} {% block content %}
<h2>Gandruk package</h2>
<h3>7 days package</h3>
<p>Price: 7000</p>
<input type="submit" name="Book" value="book"/>
<br />
{% endblock %}

site/templates/profile.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<br>

<table class="table">
	<thead>
		<tr>
			<th>S.N</th>
			<th>Name</th>
			<th>Email</th>
			<th>Address</th>
			<th>Contact</th>
			{% comment %} <th>Image</th> {% endcomment %}
            <th>Rating<th>

			


		</tr>
		
	</thead>
	<tbody>
			{% for element in profiles  %}
		 		<tr>
		 			<td>{{forloop.counter}}</td>
		 			{% comment %} <td><a href="{% url 'jobapp:employerjobdetail' job.id %}">{{job.title}}({{job.jobapplication_set.count}} applications)</a></td> {% endcomment %}
		 			<td>{{element.name}}</td>
		 			<td>{{element.email}}</td>
		 			<td>{{element.address}}</td>
		 			<td>{{element.contact}}</td>
		 			{% comment %} <td>{{element.pimage.url}}</td> {% endcomment %}
                    <td>
                       <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                       
                     </td>



		 		</tr>
	 		{% endfor %}
 	</tbody>
</table>
{% endblock %}

site/templates/registration.html
{% extends 'navbar.html' %}
{% load static %}
<body>
{% block content %}
<br>
<br>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button>register</button>
	
</form>
{% endblock %}

site/templates/search.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<html>
    <head>
        <title>Search</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    {% comment %} <body style="background-image:url({% static "image/bg.png" %})">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-dark">
                <a class="navbar-brand text-white mb-0 h1">The Movie Guy</a>
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                </ul>
            </nav>
        </header> {% endcomment %}
        <div class="jumbotron text-center">
            <div class="container">
                <form method="POST">
                    {{form.as_p}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Submit">
                </form>
            </div>
            <div class="container">
                {% if flag == False %}
                    <p> Not found </p>
                {% else %}
                    {% for i in recommended_list %}
                        {{i}}<br>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </body>
{% endblock%}
</html>